# Generated by Django 6.0.1 on 2026-04-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_height',
            field=models.CharField(default='auto', help_text='Footer height (auto or pixels like 300px)', max_length=20, verbose_name='Footer Height'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_layout',
            field=models.CharField(choices=[('4cols', '4 Columns (Full width)'), ('3cols', '3 Columns (Compact)'), ('centered', 'Centered (Single column)')], default='4cols', max_length=20, verbose_name='Footer Layout'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_link_color',
            field=models.CharField(default='#e5e7eb', max_length=20, verbose_name='Footer Link Color'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_height',
            field=models.PositiveIntegerField(default=70, help_text='Header height in pixels (50-150)', verbose_name='Header Height (px)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_layout',
            field=models.CharField(choices=[('standard', 'Standard (Logo left, nav right)'), ('centered', 'Centered (Logo center)'), ('compact', 'Compact (Reduced padding)')], default='standard', max_length=20, verbose_name='Header Layout Style'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_background_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/background/', verbose_name='Hero Background Image'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_height',
            field=models.PositiveIntegerField(default=500, help_text='Hero section height in pixels (300-800)', verbose_name='Hero Height (px)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_slideshow_speed',
            field=models.PositiveIntegerField(default=5000, help_text='Slideshow transition speed in milliseconds', verbose_name='Slideshow Speed (ms)'),
        ),
    ]
