# Generated by Django 6.0.1 on 2026-04-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='badge',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Corner Badge'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='badge_color',
            field=models.CharField(blank=True, default='accent', max_length=50, null=True, verbose_name='Badge Color'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='badge_color_2',
            field=models.CharField(blank=True, default='brand', max_length=50, null=True, verbose_name='Badge Color 2'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='badge_icon',
            field=models.CharField(blank=True, default='fire', max_length=50, null=True, verbose_name='Badge Icon'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='badge_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Badge Text'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='button1_color',
            field=models.CharField(blank=True, default='brand', max_length=50, null=True, verbose_name='Button 1 Color'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='button1_color_2',
            field=models.CharField(blank=True, default='brand-dark', max_length=50, null=True, verbose_name='Button 1 Color 2'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='button1_icon',
            field=models.CharField(blank=True, default='shopping-cart', max_length=50, null=True, verbose_name='Button 1 Icon'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='button1_text',
            field=models.CharField(blank=True, default='Shop Now', max_length=50, null=True, verbose_name='Button 1 Text'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='button1_url',
            field=models.CharField(blank=True, default='/shop/', max_length=200, null=True, verbose_name='Button 1 URL'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='button2_color',
            field=models.CharField(blank=True, default='accent', max_length=50, null=True, verbose_name='Button 2 Color'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='button2_icon',
            field=models.CharField(blank=True, default='star', max_length=50, null=True, verbose_name='Button 2 Icon'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='button2_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Button 2 Text'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='button2_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Button 2 URL'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='custom_css_class',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Custom CSS Class'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='features',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Features'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='highlight_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Highlight Text'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(default='hero/default_image.jpg', upload_to='hero/slides/', verbose_name='Slide Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image_border_radius',
            field=models.CharField(choices=[('0', 'None (Sharp)'), ('0.25rem', 'Very Small (4px)'), ('0.5rem', 'Small (8px)'), ('0.75rem', 'Medium Small (12px)'), ('1rem', 'Medium (16px)'), ('1.25rem', 'Medium Large (20px)'), ('1.5rem', 'Large (24px)'), ('2rem', 'Extra Large (32px)'), ('50%', 'Circle (50%)')], default='0', max_length=20, verbose_name='Border Radius'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image_custom_class',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Custom CSS Class'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image_height',
            field=models.CharField(choices=[('auto', 'Auto (Original)'), ('200px', '200px'), ('250px', '250px'), ('300px', '300px'), ('350px', '350px'), ('400px', '400px'), ('450px', '450px'), ('500px', '500px'), ('100%', '100%'), ('100vh', '100vh (Full Screen)')], default='100vh', max_length=20, verbose_name='Image Height'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image_hover_effect',
            field=models.BooleanField(default=False, verbose_name='Hover Scale Effect'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image_mobile_height',
            field=models.CharField(choices=[('auto', 'Auto (Original)'), ('200px', '200px'), ('250px', '250px'), ('300px', '300px'), ('350px', '350px'), ('400px', '400px'), ('450px', '450px'), ('500px', '500px'), ('100%', '100%'), ('100vh', '100vh (Full Screen)')], default='auto', max_length=20, verbose_name='Mobile Image Height'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image_mobile_width',
            field=models.CharField(choices=[('auto', 'Auto (Original)'), ('100%', 'Full Width (100%)'), ('90%', '90%'), ('80%', '80%'), ('70%', '70%'), ('60%', '60%'), ('50%', '50%'), ('40%', '40%'), ('300px', '300px'), ('350px', '350px'), ('400px', '400px'), ('450px', '450px'), ('500px', '500px'), ('550px', '550px'), ('600px', '600px')], default='100%', max_length=20, verbose_name='Mobile Image Width'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image_shadow',
            field=models.BooleanField(default=False, verbose_name='Add Shadow Effect'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image_shadow_size',
            field=models.CharField(choices=[('sm', 'Small Shadow'), ('md', 'Medium Shadow'), ('lg', 'Large Shadow'), ('xl', 'Extra Large Shadow'), ('none', 'No Shadow')], default='none', max_length=20, verbose_name='Shadow Size'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image_width',
            field=models.CharField(choices=[('auto', 'Auto (Original)'), ('100%', 'Full Width (100%)'), ('90%', '90%'), ('80%', '80%'), ('70%', '70%'), ('60%', '60%'), ('50%', '50%'), ('40%', '40%'), ('300px', '300px'), ('350px', '350px'), ('400px', '400px'), ('450px', '450px'), ('500px', '500px'), ('550px', '550px'), ('600px', '600px')], default='100%', max_length=20, verbose_name='Image Width'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='layout_style',
            field=models.CharField(choices=[('image_only', '🎯 Image Only Slider (Full Screen Image)'), ('default', 'Default (Original Design)'), ('centered', 'Centered Layout'), ('split', 'Split Screen (Image + Text)'), ('fullscreen', 'Full Screen Overlay'), ('minimal', 'Minimal Design'), ('card', 'Card Style'), ('hero', 'Hero Bold'), ('gradient', 'Gradient Overlay')], default='default', max_length=20, verbose_name='Layout Style'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='price_label',
            field=models.CharField(blank=True, default='From', max_length=50, null=True, verbose_name='Price Label'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='price_tag',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Price Tag'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='price_tag_color',
            field=models.CharField(blank=True, default='brand', max_length=50, null=True, verbose_name='Price Tag Color'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='price_tag_color_2',
            field=models.CharField(blank=True, default='brand-dark', max_length=50, null=True, verbose_name='Price Tag Color 2'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='subtitle',
            field=models.TextField(blank=True, default='Cutting-edge technology with exceptional performance.', null=True, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='title',
            field=models.CharField(blank=True, default='Premium Smartphones', max_length=200, null=True, verbose_name='Slide Title'),
        ),
    ]
