# Generated by Django 6.0.1 on 2026-04-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0002_alter_heroslide_badge_alter_heroslide_badge_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='icon',
            field=models.CharField(blank=True, default='fas fa-tag', max_length=50, null=True),
        ),
    ]
