# Generated by Django 6.0.1 on 2026-04-15 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0002_sitesettings_footer_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='description',
        ),
    ]
