# Generated by Django 6.0.1 on 2026-04-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0003_remove_brand_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='animation_effect',
            field=models.CharField(choices=[('fadeInUp', 'Fade In Up'), ('fadeIn', 'Fade In'), ('zoomIn', 'Zoom In'), ('slideInLeft', 'Slide In Left'), ('slideInRight', 'Slide In Right'), ('bounce', 'Bounce'), ('flipInX', 'Flip In X'), ('rotateIn', 'Rotate In'), ('lightSpeedIn', 'Light Speed In')], default='fadeInUp', max_length=30, verbose_name='Animation Effect'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='background_pattern',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Background Pattern'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='button_delay',
            field=models.IntegerField(default=300, help_text='Delay in ms', verbose_name='Button Animation Delay'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='content_alignment',
            field=models.CharField(choices=[('left', 'Left Aligned'), ('center', 'Center Aligned'), ('right', 'Right Aligned')], default='left', max_length=10, verbose_name='Content Alignment'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='custom_css_class',
            field=models.CharField(blank=True, max_length=100, verbose_name='Custom CSS Class'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='layout_style',
            field=models.CharField(choices=[('default', 'Default (Original Design)'), ('centered', 'Centered Layout'), ('split', 'Split Screen (Image + Text)'), ('fullscreen', 'Full Screen Overlay'), ('minimal', 'Minimal Design'), ('card', 'Card Style'), ('hero', 'Hero Bold'), ('gradient', 'Gradient Overlay')], default='default', max_length=20, verbose_name='Layout Style'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='side_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/side_images/', verbose_name='Side Image (for Split Layout)'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='slide_accent_color',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Slide Accent Color'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='slide_bg_color',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Slide Background Color'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='slide_overlay_opacity',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='0 to 1', max_digits=3, verbose_name='Overlay Opacity'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='slide_text_color',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Slide Text Color'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='subtitle_delay',
            field=models.IntegerField(default=200, help_text='Delay in ms', verbose_name='Subtitle Animation Delay'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='theme_style',
            field=models.CharField(choices=[('light', 'Light Theme'), ('dark', 'Dark Theme'), ('glass', 'Glassmorphism'), ('neon', 'Neon Glow'), ('gradient', 'Gradient Theme')], default='light', max_length=20, verbose_name='Theme Style'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='title_delay',
            field=models.IntegerField(default=100, help_text='Delay in ms', verbose_name='Title Animation Delay'),
        ),
    ]
