# Generated by Django 6.0.1 on 2026-04-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0004_heroslide_animation_effect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='highlight_font_size',
            field=models.IntegerField(default=36, help_text='Highlight text font size in pixels', verbose_name='Highlight Font Size'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='image_border_radius',
            field=models.CharField(choices=[('0', 'None (Sharp)'), ('0.25rem', 'Very Small (4px)'), ('0.5rem', 'Small (8px)'), ('0.75rem', 'Medium Small (12px)'), ('1rem', 'Medium (16px)'), ('1.25rem', 'Medium Large (20px)'), ('1.5rem', 'Large (24px)'), ('2rem', 'Extra Large (32px)'), ('50%', 'Circle (50%)')], default='1rem', max_length=20, verbose_name='Border Radius'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='image_custom_class',
            field=models.CharField(blank=True, max_length=100, verbose_name='Custom CSS Class'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='image_height',
            field=models.CharField(choices=[('auto', 'Auto (Original)'), ('200px', '200px'), ('250px', '250px'), ('300px', '300px'), ('350px', '350px'), ('400px', '400px'), ('450px', '450px'), ('500px', '500px'), ('100%', '100%')], default='auto', max_length=20, verbose_name='Image Height'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='image_hover_effect',
            field=models.BooleanField(default=True, verbose_name='Hover Scale Effect'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='image_hover_scale',
            field=models.DecimalField(decimal_places=2, default=1.05, help_text='1.05 = 5% zoom', max_digits=3, verbose_name='Hover Scale'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='image_mobile_height',
            field=models.CharField(choices=[('auto', 'Auto (Original)'), ('200px', '200px'), ('250px', '250px'), ('300px', '300px'), ('350px', '350px'), ('400px', '400px'), ('450px', '450px'), ('500px', '500px'), ('100%', '100%')], default='auto', max_length=20, verbose_name='Mobile Image Height'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='image_mobile_width',
            field=models.CharField(choices=[('auto', 'Auto (Original)'), ('100%', 'Full Width (100%)'), ('90%', '90%'), ('80%', '80%'), ('70%', '70%'), ('60%', '60%'), ('50%', '50%'), ('40%', '40%'), ('300px', '300px'), ('350px', '350px'), ('400px', '400px'), ('450px', '450px'), ('500px', '500px'), ('550px', '550px'), ('600px', '600px')], default='80%', max_length=20, verbose_name='Mobile Image Width'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='image_object_fit',
            field=models.CharField(choices=[('cover', 'Cover (Fill & Crop)'), ('contain', 'Contain (Keep Ratio)'), ('fill', 'Fill (Stretch)'), ('scale-down', 'Scale Down'), ('none', 'None (Original)')], default='cover', max_length=20, verbose_name='Object Fit'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='image_opacity',
            field=models.IntegerField(default=100, help_text='0 to 100', verbose_name='Image Opacity (%)'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='image_position',
            field=models.CharField(choices=[('center center', 'Center'), ('center top', 'Top Center'), ('center bottom', 'Bottom Center'), ('left center', 'Left Center'), ('right center', 'Right Center'), ('left top', 'Top Left'), ('right top', 'Top Right'), ('left bottom', 'Bottom Left'), ('right bottom', 'Bottom Right')], default='center center', max_length=30, verbose_name='Image Position'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='image_shadow',
            field=models.BooleanField(default=True, verbose_name='Add Shadow Effect'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='image_shadow_size',
            field=models.CharField(choices=[('sm', 'Small Shadow'), ('md', 'Medium Shadow'), ('lg', 'Large Shadow'), ('xl', 'Extra Large Shadow'), ('none', 'No Shadow')], default='lg', max_length=20, verbose_name='Shadow Size'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='image_width',
            field=models.CharField(choices=[('auto', 'Auto (Original)'), ('100%', 'Full Width (100%)'), ('90%', '90%'), ('80%', '80%'), ('70%', '70%'), ('60%', '60%'), ('50%', '50%'), ('40%', '40%'), ('300px', '300px'), ('350px', '350px'), ('400px', '400px'), ('450px', '450px'), ('500px', '500px'), ('550px', '550px'), ('600px', '600px')], default='auto', max_length=20, verbose_name='Image Width'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='subtitle_font_size',
            field=models.IntegerField(default=20, help_text='Subtitle font size in pixels', verbose_name='Subtitle Font Size'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='title_font_size',
            field=models.IntegerField(default=48, help_text='Title font size in pixels', verbose_name='Title Font Size'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='animation_effect',
            field=models.CharField(choices=[('fadeInUp', 'Fade In Up'), ('fadeIn', 'Fade In'), ('zoomIn', 'Zoom In'), ('slideInLeft', 'Slide In Left'), ('slideInRight', 'Slide In Right'), ('bounce', 'Bounce'), ('flipInX', 'Flip In X'), ('rotateIn', 'Rotate In'), ('lightSpeedIn', 'Light Speed In'), ('none', 'No Animation')], default='fadeInUp', max_length=30, verbose_name='Animation Effect'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='theme_style',
            field=models.CharField(choices=[('light', 'Light Theme'), ('dark', 'Dark Theme'), ('glass', 'Glassmorphism'), ('neon', 'Neon Glow'), ('gradient', 'Gradient Theme'), ('none', 'None (No Theme)')], default='light', max_length=20, verbose_name='Theme Style'),
        ),
    ]
