# Generated by Django 6.0.1 on 2026-04-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0020_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Premium Smartphones', max_length=200, verbose_name='Slide Title')),
                ('highlight_text', models.CharField(blank=True, max_length=100, verbose_name='Highlight Text')),
                ('subtitle', models.TextField(default='Cutting-edge technology with exceptional performance.', verbose_name='Subtitle')),
                ('badge_text', models.CharField(blank=True, max_length=100, verbose_name='Badge Text')),
                ('badge_icon', models.CharField(default='fire', max_length=50, verbose_name='Badge Icon')),
                ('badge_color', models.CharField(default='accent', max_length=50, verbose_name='Badge Color')),
                ('badge_color_2', models.CharField(default='brand', max_length=50, verbose_name='Badge Color 2')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero/slides/', verbose_name='Slide Image')),
                ('button1_text', models.CharField(default='Shop Now', max_length=50, verbose_name='Button 1 Text')),
                ('button1_url', models.CharField(default='/shop/', max_length=200, verbose_name='Button 1 URL')),
                ('button1_icon', models.CharField(default='shopping-cart', max_length=50, verbose_name='Button 1 Icon')),
                ('button1_color', models.CharField(default='brand', max_length=50, verbose_name='Button 1 Color')),
                ('button1_color_2', models.CharField(default='brand-dark', max_length=50, verbose_name='Button 1 Color 2')),
                ('button2_text', models.CharField(blank=True, max_length=50, verbose_name='Button 2 Text')),
                ('button2_url', models.CharField(blank=True, max_length=200, verbose_name='Button 2 URL')),
                ('button2_icon', models.CharField(default='star', max_length=50, verbose_name='Button 2 Icon')),
                ('button2_color', models.CharField(default='accent', max_length=50, verbose_name='Button 2 Color')),
                ('price_tag', models.CharField(blank=True, max_length=50, verbose_name='Price Tag')),
                ('price_label', models.CharField(default='From', max_length=50, verbose_name='Price Label')),
                ('price_tag_color', models.CharField(default='brand', max_length=50, verbose_name='Price Tag Color')),
                ('price_tag_color_2', models.CharField(default='brand-dark', max_length=50, verbose_name='Price Tag Color 2')),
                ('badge', models.CharField(blank=True, max_length=100, verbose_name='Corner Badge')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Rating')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='Features')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='favicon',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='logo',
        ),
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='accent_color',
            field=models.CharField(default='#f59e0b', max_length=20, verbose_name='Accent Color'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_address',
            field=models.TextField(blank=True, verbose_name='Office Address'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(default='support@jadidtechnology.com', max_length=254, verbose_name='Contact Email'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(default='+880123456789', max_length=20, verbose_name='Contact Phone'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='custom_css',
            field=models.TextField(blank=True, verbose_name='Custom CSS'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='custom_js',
            field=models.TextField(blank=True, verbose_name='Custom JavaScript'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_pixel_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Facebook Pixel ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_bg_color',
            field=models.CharField(default='#111827', max_length=20, verbose_name='Footer Background Color'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_copyright',
            field=models.CharField(default='© 2024 Jadid Technology. All rights reserved.', max_length=200, verbose_name='Copyright Text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text_color',
            field=models.CharField(default='#9ca3af', max_length=20, verbose_name='Footer Text Color'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Google Analytics ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_bg_color',
            field=models.CharField(default='#ffffff', max_length=20, verbose_name='Header Background Color'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_sticky',
            field=models.BooleanField(default=True, verbose_name='Sticky Header'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_text_color',
            field=models.CharField(default='#1f2937', max_length=20, verbose_name='Header Text Color'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_bg_color',
            field=models.CharField(default='#6366f1', max_length=20, verbose_name='Hero Background Color'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_button_text',
            field=models.CharField(default='Shop Now', max_length=50, verbose_name='Hero Button Text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_button_url',
            field=models.CharField(default='/shop/', max_length=200, verbose_name='Hero Button URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_enabled',
            field=models.BooleanField(default=True, verbose_name='Enable Hero Section'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_highlight',
            field=models.CharField(blank=True, default='Best Deals', max_length=100, verbose_name='Hero Highlight'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='site/hero/', verbose_name='Hero Image 1'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='site/hero/', verbose_name='Hero Image 2'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='site/hero/', verbose_name='Hero Image 3'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.TextField(default='Discover the latest smartphones, laptops, and gadgets at best prices', verbose_name='Hero Subtitle'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(default='Welcome to Jadid Technology', max_length=200, verbose_name='Hero Title'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='LinkedIn URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_message',
            field=models.TextField(default='Site is under maintenance. Please check back soon!', verbose_name='Maintenance Message'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_mode',
            field=models.BooleanField(default=False, verbose_name='Maintenance Mode'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Default Meta Description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500, verbose_name='Default Meta Keywords'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Default Meta Title'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(default='#6366f1', max_length=20, verbose_name='Primary Color'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='secondary_color',
            field=models.CharField(default='#3b82f6', max_length=20, verbose_name='Secondary Color'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_newsletter',
            field=models.BooleanField(default=True, verbose_name='Show Newsletter Section'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_top_bar',
            field=models.BooleanField(default=True, verbose_name='Show Top Bar'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_favicon',
            field=models.ImageField(blank=True, null=True, upload_to='site/favicon/', verbose_name='Favicon Icon'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/logo/', verbose_name='Site Logo'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_tagline',
            field=models.CharField(blank=True, default='Premium Tech Store', max_length=200, verbose_name='Site Tagline'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='top_bar_text',
            field=models.CharField(blank=True, default='Free Shipping on orders over $50', max_length=500, verbose_name='Top Bar Text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_url',
            field=models.URLField(blank=True, verbose_name='Twitter URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='YouTube URL'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Jadid Technology', max_length=100, verbose_name='Site Name'),
        ),
    ]
